### ISSUE TITLE
Documentation build broken

### ISSUE THREAD

**Issue by roflmaostc** [RainerHeintzmann/PointSpreadFunctions.jl#12]
```julia
julia> ]activate docs/

julia> include("make.jl")
```

This is due to that Documenter updated and changed the behavior in case of warnings.

**Comment by roflmaostc** [comment]
https://github.com/JuliaDocs/Documenter.jl/blob/v1.0.0/CHANGELOG.md

**Comment by RainerHeintzmann** [comment]
should be fixed now. Only the fontsize seems a little large to me.
