### ISSUE TITLE
DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 3 and 4

### ISSUE THREAD

**Issue by Zhang-jingxiang** [RainerHeintzmann/PointSpreadFunctions.jl#16]
Hello, 
I followed the steps in the guide to use PointSpreadFunctions. However, the following error is always generated, how to fix it, Thank you!
Here's my code.
```
using PointSpreadFunctions
lam_em = 0.5; NA = 1.4; n = 1.52
lam_ex = 0.488
pp = PSFParams(lam_em, NA, n; pol = pol_x); 

sz = (256,256,256)
sampling = (0.06, 0.06,0.06)  
print(pp)
p = psf(sz,pp;sampling = sampling);
```

```
DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 3 and 4

Stacktrace:
  [1] _bcs1
    @ .\broadcast.jl:555 [inlined]
  [2] _bcs
    @ .\broadcast.jl:549 [inlined]
  [3] broadcast_shape(::Tuple{Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64}})
    @ Base.Broadcast .\broadcast.jl:543
  [4] combine_axes
    @ .\broadcast.jl:524 [inlined]
  [5] _axes
    @ .\broadcast.jl:236 [inlined]
  [6] axes
    @ .\broadcast.jl:234 [inlined]
  [7] combine_axes
    @ .\broadcast.jl:524 [inlined]
  [8] _axes
    @ .\broadcast.jl:236 [inlined]
  [9] axes
    @ .\broadcast.jl:234 [inlined]
 [10] copy
    @ .\broadcast.jl:1115 [inlined]
 [11] materialize
    @ .\broadcast.jl:903 [inlined]
...
    @ PointSpreadFunctions C:\Users\leilab\.julia\packages\PointSpreadFunctions\KTdtU\src\PointSpreadFunctions.jl:55
 [16] psf(sz::Tuple{Int64, Int64, Int64}, pp::PSFParams; nps::@Kwargs{sampling::Tuple{Float64, Float64, Float64}})
    @ PointSpreadFunctions C:\Users\leilab\.julia\packages\PointSpreadFunctions\KTdtU\src\PointSpreadFunctions.jl:525
 [17] top-level scope
    @ d:\code\000 JSFR-NL\002code\myJSFR\test_SIM.ipynb:1
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?eb2e067d-91b8-411b-8be7-8651e7fdd5ae) or open in a [text editor](command:workbench.action.openLargeOutput?eb2e067d-91b8-411b-8be7-8651e7fdd5ae). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```

**Comment by RainerHeintzmann** [comment]
Can you try "]update" and check again?
If it still does not work, can you post "]st"?

**Comment by Zhang-jingxiang** [comment]
It's still not working. I've also changed my latest version to the 1.7.1 version used in your video and it still doesn't work.
Here is my status
```
(v1.7) pkg> st
      Status `C:\Users\leilab\.julia\environments\v1.7\Project.toml`
  [a7ea9a99] StructuredIlluminationMicroscopy v0.1.0 `https://github.com/RainerHeintzmann/StructuredIlluminationMicroscopy.jl#main`
  [5e47fb64] TestImages v1.8.0
```
 Since I changed the version, many of the packages in it are gone
Thanks!

**Comment by RainerHeintzmann** [comment]
Can you activate the environment in the installation directory and show the status?

**Comment by Zhang-jingxiang** [comment]
Did you mean "] activate" to return the global environment? 
```
(@v1.7) pkg> activate
  Activating project at `C:\Users\leilab\.julia\packages\environments\v1.7`

(@v1.7) pkg> status
      Status `C:\Users\leilab\.julia\packages\environments\v1.7\Project.toml` (empty project)
```

**Comment by RainerHeintzmann** [comment]
I mean activating the environment in the package folder. Not the test. CD there and type ']activate'

**Comment by Zhang-jingxiang** [comment]
```
julia> pwd()
"C:\\Users\\leilab\\.julia\\packages"

(@v1.7) pkg> activate
  Activating project at `C:\Users\leilab\.julia\packages\environments\v1.7`

(@v1.7) pkg> status
      Status `C:\Users\leilab\.julia\packages\environments\v1.7\Project.toml` (empty project)
```

**Comment by RainerHeintzmann** [comment]
The problem is the Versions of the various packages, which prevented you from updating `PointSpreadFunctions.jl` to a recent version. The culprit was `SeparableFunctions.jl`. I now made a new release (0.1.1.) of that package (please wait a few minutes until this version shows as a release on the web-page). Try a new installation in  a newly activated Folder (never use the global folder to install stuff) and make sure that you use NDTools.jl 0.7 and SeparableFunctions.jl 0.1.1 and everything should run fine (hopefully).

**Comment by RainerHeintzmann** [comment]
Sorry. I finally got it working, but am not really sure what the problem is.
Solution:
1) deinstall everything
2) Install "SeparableFunctions.jl", by itself in a freshly activated empty environment. Should be version 0.1.1.
3) pin the version "]pin SeparableFunctions"
4) install the "]add StructureIlluminationMicroscopy.jl" repo
5) "]add PointSpreadFunctions"  this should be version 0.4.2

**Comment by Zhang-jingxiang** [comment]
I‘m really appreciate your help!!! The project is now up and running!
