### ISSUE TITLE
Return type of ISM PSF is an any Vector

### ISSUE THREAD

**Issue by roflmaostc** [RainerHeintzmann/PointSpreadFunctions.jl#7]
Wouldn't it be better to return a 4D array where one dimension represents the different pinholes?

```julia
λ_em = 0.5; NA = 1.4; n = 1.52
λ_ex = 0.488 # only needed for some PointSpreadFunctions, such as confocal, ISM or TwoPhoton
pp = PSFParams(λ_em, NA, n; pol=pol_x)

pp_ex = PSFParams(λ_ex, NA, n; mode=ModeWidefield, aplanatic=aplanatic_illumination); 


#sz = (256, 256, 256)
sampling = (0.04,0.04,0.04);
sz = (128,128,128)
print(pp)

pp_ism = PSFParams(λ_em, NA, n; mode=ModeISM); 
@time p_ism = psf(sz, pp_ism; pp_ex=pp_ex, sampling=sampling, pinhole_dist=0.12);

#25-element Vector{Any}:
 [1.4236383f-10 1.6749102f-10 … 1.792323f-10 1.6628918f-10; 1.799875f-10 2.2861517f-10 … 1.9823553f-10 1.8760402f-10; … ; 1.7487184f-10 1.8702395f-10 … 2.0741721f-10 2.1865709f-10; 1.6082255f-10 1.8074786f-10 … 2.1083522f-10 2.0267038f-10;;; 2.1477528f
```

**Comment by RainerHeintzmann** [comment]
A vector of `Any` is of course not a good choice. But I think a vector of the type of each individual pinhole psf would be suitable. If really needed the user can still stack them, but I prefer to keep them as a vector. This also avoids the problem that a raw PSF can be 2D or 3D which may then alter the stacking dimension etc. Another reason is that there is no uniformity to the pinhole position. It is can be a flattened 2D array or positions etc. but an n-dimensional dataset somehow seems to imply a uniform spacing along each dimension.  Note that the pinhole-positions can be supplied as a vector and therefore it also makes sense to obtain a vector of output psfs.

**Comment by RainerHeintzmann** [comment]
.. I fixed the `Any` in the return type.
