### ISSUE TITLE
Calculation of the confocal PSF for an offset Pinhole

### ISSUE THREAD

**Issue by roflmaostc** [RainerHeintzmann/PointSpreadFunctions.jl#8]
Hi,

I was wondering how you calculate the PSF of a confocal system with a pinhole place offset to the optical axis.

If I understand correctly, you bascially do:

```julia
psf_em = fft(psf_em, (1,2))
my_pinhole_ft = exp_ikx_rfft(eltype(psf_em), sz, shift_by=p) .* pinhole_ft(sz, pp_em, pinhole_pix)
my_em = ifft(fft_psf_em .* my_pinhole_ft, (1,2))
psf_final = my_em .* psf_ex
```

So essentially you're multiplying excitation and emission PSF. But the emission PSF is actually convolved with a pinhole before.

I think, following "Introduction to Optical Microscopy" it should be rather a correlation between PSF and pinhole.
What do you think?

For most pinholes, this doesn't make a big difference, but for asymmetric it would actually do.

Best,

Felix

**Comment by RainerHeintzmann** [comment]
Yes, if you mean `fft_psf_em` in the first row. Thinking about it a little, I think it should be a convolution, if you describe the pinhole (whichever asymmetric shape it may have) as geometrically back-projected into the object space. If the pinhole was a delta shifted to +x, then the detection point spread function would be sensitive if the object scan reached a place near the position +x. Thus the psf is also sensitive near +x, which shows this should be a convolution of the widefield detection psf with the pinhole shape, not a correlation.
Yet, I guess this is a question about how you define the coordinate system of the pinhole. In other words the sign of `p` in your example, provided that the pinhole is centro-symmetric.

**Comment by RainerHeintzmann** [comment]
The confocal psf calculation directly supports offset pinholes. Here is an example:
`
pp_em = PSFParams(0.488, 1.4, 1.518; mode=ModeConfocal);
pp_ex = PSFParams(0.520, 1.4, 1.518);
h = psf((128,128), pp_em, pp_ex=pp_ex, pinhole=0.2, sampling=(0.04, 0.04), pinhole_positions=[(8.0,2.0)])
`
Note that the `pinhole_positions` argument is in pixels.
